# domain/stores/order_interfaces.py
# -*- coding: utf-8 -*-
"""
精细化接口，将 AbstractOrderLedger 拆分为小接口。
"""
from abc import ABC, abstractmethod
from typing import Dict, Any, Optional


class OrderRepository(ABC):
    @abstractmethod
    def add_pending_order(self, cl_ord_id: str, data: Dict[str, Any]) -> None: ...
    @abstractmethod
    def remove_pending_order(self, cl_ord_id: str) -> None: ...
    @abstractmethod
    def get_pending_order(self, cl_ord_id: str) -> Optional[Dict[str, Any]]: ...
    @abstractmethod
    def get_all_pending_orders(self) -> Dict[str, Dict[str, Any]]: ...


class ConditionTriggerRepo(ABC):
    @abstractmethod
    def add_condition_trigger(self, cl_ord_id: str, trigger_info: Dict[str, Any]) -> None: ...
    @abstractmethod
    def remove_condition_trigger(self, cl_ord_id: str) -> None: ...
    @abstractmethod
    def get_condition_trigger(self, cl_ord_id: str) -> Optional[Dict[str, Any]]: ...


class CancelLockManager(ABC):
    @abstractmethod
    def acquire_cancel_lock(self, symbol: str) -> bool: ...
    @abstractmethod
    def release_cancel_lock(self, symbol: str) -> None: ...
    @abstractmethod
    def mark_cancelled(self, symbol: str) -> None: ...
    @abstractmethod
    def pop_cancelled(self, symbol: str) -> bool: ...
    @abstractmethod
    def is_cancelling(self, symbol: str) -> bool: ...


class SleepStateManager(ABC):
    @abstractmethod
    def get_sleep_state(self) -> bool: ...
    @abstractmethod
    def set_sleep_state(self, state: bool) -> None: ...
    @abstractmethod
    def is_condition8_sleeping(self) -> bool: ...


class Condition8OrderTracker(ABC):
    @abstractmethod
    def cancel_condition8_opposite(self, symbol: str, keep_cl_ord_id: str) -> None: ...
    @abstractmethod
    def get_condition8_pending_pool(self, symbol: str) -> Dict[str, str]: ...
    @abstractmethod
    def record_condition8_done_price(self, symbol: str, done_price: float) -> None: ...
    @abstractmethod
    def clear_condition8_state(self, symbol: str) -> None: ...